//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string License_Key {
            get {
                return ((string)(this["License_Key"]));
            }
            set {
                this["License_Key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("226, 226, 226")]
        public global::System.Drawing.Color Phone_Ico_TopLeft {
            get {
                return ((global::System.Drawing.Color)(this["Phone_Ico_TopLeft"]));
            }
            set {
                this["Phone_Ico_TopLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("224, 224, 224")]
        public global::System.Drawing.Color Daily_Workout_Menu {
            get {
                return ((global::System.Drawing.Color)(this["Daily_Workout_Menu"]));
            }
            set {
                this["Daily_Workout_Menu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("224, 224, 224")]
        public global::System.Drawing.Color Survival_Index {
            get {
                return ((global::System.Drawing.Color)(this["Survival_Index"]));
            }
            set {
                this["Survival_Index"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18, 18, 18")]
        public global::System.Drawing.Color Virtual_Universe_Button {
            get {
                return ((global::System.Drawing.Color)(this["Virtual_Universe_Button"]));
            }
            set {
                this["Virtual_Universe_Button"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WhiteSmoke")]
        public global::System.Drawing.Color Rule_i_Button {
            get {
                return ((global::System.Drawing.Color)(this["Rule_i_Button"]));
            }
            set {
                this["Rule_i_Button"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color Sepal_Gold_Button {
            get {
                return ((global::System.Drawing.Color)(this["Sepal_Gold_Button"]));
            }
            set {
                this["Sepal_Gold_Button"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18, 18, 18")]
        public global::System.Drawing.Color Sepal_Crimson_Button {
            get {
                return ((global::System.Drawing.Color)(this["Sepal_Crimson_Button"]));
            }
            set {
                this["Sepal_Crimson_Button"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color Fights_Slider {
            get {
                return ((global::System.Drawing.Color)(this["Fights_Slider"]));
            }
            set {
                this["Fights_Slider"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("228, 202, 147")]
        public global::System.Drawing.Color Fight_Group_Ico {
            get {
                return ((global::System.Drawing.Color)(this["Fight_Group_Ico"]));
            }
            set {
                this["Fight_Group_Ico"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WhiteSmoke")]
        public global::System.Drawing.Color Fight_Ended_Trigger {
            get {
                return ((global::System.Drawing.Color)(this["Fight_Ended_Trigger"]));
            }
            set {
                this["Fight_Ended_Trigger"] = value;
            }
        }
    }
}
